name: Pull/Run Unit tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited]
  workflow_call:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test E2E'
    steps:
      - uses: actions/checkout@v4
        with:
          repository: modbus2mqtt/modbus2mqtt.dev
          path: .
      - name: initialize environment for this
        run: |
          gh auth status
          bin/pulls.py -p repositories.test.json init -b main
          bin/pulls.py -p repositories.test.json syncpull ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} pull${{github.event.number}} "pull${{github.event.pull_request.body}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Run tests
        id: test
        run: |
          bin/pulls.py -p repositories.test.json testorwait ${{github.event.pull_request.base.repo.name}}:${{github.event.number}} "${{github.event.pull_request.body}}"    
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name "Cypress tests"
        if: steps.test.outputs.type == 'testrunner'
      - name: Packages and system services for e2e Tests
        run: server/cypress/servers/installPackages
      - name: Local services for e2e Tests
        if: steps.test.outputs.type == 'testrunner'
        run: server/cypress/servers/startRunningServers
      - name: Cypress run
        if: steps.test.outputs.type == 'testrunner'
        uses: cypress-io/github-action@v6
        with:
          working-directory: server
          install: false


       
      
